export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_COOKIE_NAME: "bc_access_token",
  REFRESH_TOKEN_COOKIE_NAME: "bc_refresh_token",
  ACCESS_TOKEN_EXPIRES_IN: "15m",
  REFRESH_TOKEN_EXPIRES_IN: "30d",
  TWO_FACTOR_CHALLENGE_EXPIRES_IN: "10m",
  ACCESS_TOKEN_MAX_AGE_MS: 15 * 60 * 1000,
  REFRESH_TOKEN_MAX_AGE_MS: 30 * 24 * 60 * 60 * 1000,
  TWO_FACTOR_CODE_TTL_MS: 10 * 60 * 1000,
  TWO_FACTOR_RESEND_COOLDOWN_MS: 30 * 1000,
  PASSWORD_RESET_TOKEN_TTL_MS: 60 * 60 * 1000,
} as const;
